name: screen_recorder
description: Lightweight Android screen recorder with a Flutter UI and native Java capture pipeline.
publish_to: 'none'
version: 0.4.0+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
