[versions]
agp = "8.7.3"
core = "1.15.0"
appcompat = "1.7.0"
documentfile = "1.0.1"

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
